### PR TITLE
Correct return parameter order; fix rune counts

### LINKED ISSUE #487: Event file writes sometimes have Location in Arg
We can get:
"C1:M C2:x Q0:48 Q1:52 OQ0:49 OQ1:49 Flag:11 Text:Look Arg:/Users/flux/dev/edwood/cmd/win/win Loc:/Users/flux/dev/edwood/cmd/win/+win:#117,#120"

instead of
"C1:M C2:x Q0:48 Q1:52 OQ0:49 OQ1:49 Flag:11 Text:Look Arg:/Users/flux/dev/edwood/cmd/win/+win:#117,#120" Loc:/Users/flux/dev/edwood/cmd/win/+win:#117,#120"

Working on a reliable repro - this showed up cleanly (and repeatably) while working on win.

### PR DESCRIPTION
**Pull request by paul-lalonde**
Fix #487; possibly also #470

### CODE REVIEW

File: exec.go [hunk 1]
```diff
@@ -223,9 +223,9 @@ func execute(t *Text, aq0 int, aq1 int, external bool, argt *Text) {
 			}
 		}
 		if a != "" {
-			t.w.Eventf("%c0 0 0 %d %v\n", c, len(a), a)
+			t.w.Eventf("%c0 0 0 %d %v\n", c, len([]rune(a)), a)
 			if aa != "" {
-				t.w.Eventf("%c0 0 0 %d %v\n", c, len(aa), aa)
+				t.w.Eventf("%c0 0 0 %d %v\n", c, len([]rune(aa)), aa)
```
Comment (paul-lalonde) [inline exec.go:228]: And now I'm not sure about this one.  I'd *like* the interface across the channel to be counted in runes, not bytes. But I have only the evidence of win's implementation, and of Russ's acme port that this is the case.
We need tests.

Comment (paul-lalonde) [reply exec.go:228]: Ok, carefully re-reading the man page, russ's go code, the original acme code, I believe that yes, the "number of characters" refers to runes, not bytes.  But the rune counts change should be a separate CL.  I'll split it off.
